"""initial schema

Revision ID: 116cb2da1cef
Revises: 
Create Date: 2026-07-02 22:34:48.455521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '116cb2da1cef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('end_user_device', 'mobile', 'server', 'network_device', 'iot_ot', 'removable_media', 'cloud_service', 'software', name='assettype'), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custodian', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criticality', sa.Enum('critical', 'high', 'medium', 'low', name='criticality'), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('discovered', 'active', 'decommissioned', name='lifecyclestatus'), nullable=False),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discoveryrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('kev_flag', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_cve_id'), 'vulnerability', ['cve_id'], unique=True)
    op.create_table('assetinterface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uplink_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetinterface_asset_id'), 'assetinterface', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assetinterface_ip'), 'assetinterface', ['ip'], unique=False)
    op.create_index(op.f('ix_assetinterface_mac'), 'assetinterface', ['mac'], unique=False)
    op.create_table('assetservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetservice_asset_id'), 'assetservice', ['asset_id'], unique=False)
    op.create_table('cirelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('related_asset_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cirelationship_asset_id'), 'cirelationship', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cirelationship_related_asset_id'), 'cirelationship', ['related_asset_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.Column('ad_hoc_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('exposure', sa.Enum('internet_facing', 'internal', name='exposure'), nullable=False),
    sa.Column('detected_date', sa.DateTime(), nullable=False),
    sa.Column('sla_due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'mitigated', 'accepted', 'closed', name='findingstatus'), nullable=False),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_asset_id'), 'finding', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_asset_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_cirelationship_related_asset_id'), table_name='cirelationship')
    op.drop_index(op.f('ix_cirelationship_asset_id'), table_name='cirelationship')
    op.drop_table('cirelationship')
    op.drop_index(op.f('ix_assetservice_asset_id'), table_name='assetservice')
    op.drop_table('assetservice')
    op.drop_index(op.f('ix_assetinterface_mac'), table_name='assetinterface')
    op.drop_index(op.f('ix_assetinterface_ip'), table_name='assetinterface')
    op.drop_index(op.f('ix_assetinterface_asset_id'), table_name='assetinterface')
    op.drop_table('assetinterface')
    op.drop_index(op.f('ix_vulnerability_cve_id'), table_name='vulnerability')
    op.drop_table('vulnerability')
    op.drop_table('discoveryrun')
    op.drop_table('asset')
    # ### end Alembic commands ###
