"""add vendor to asset interface

Revision ID: 1dd04ad84630
Revises: a728f248bb42
Create Date: 2026-07-04 17:32:59.195396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dd04ad84630'
down_revision: Union[str, Sequence[str], None] = 'a728f248bb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetinterface', sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assetinterface', 'vendor')
    # ### end Alembic commands ###
