"""add vendor and vendor_locked to asset

Revision ID: 2a8bdd9a266d
Revises: 5dcdaa3ce36e
Create Date: 2026-07-09 10:36:40.931546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a8bdd9a266d'
down_revision: Union[str, Sequence[str], None] = '5dcdaa3ce36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset', sa.Column('vendor_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('asset', 'vendor_locked', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'vendor_locked')
    op.drop_column('asset', 'vendor')
    # ### end Alembic commands ###
