"""add hostname_locked to asset

Revision ID: 375c4f8896d8
Revises: 1dd04ad84630
Create Date: 2026-07-04 18:33:14.789056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '375c4f8896d8'
down_revision: Union[str, Sequence[str], None] = '1dd04ad84630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'asset',
        sa.Column('hostname_locked', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('asset', 'hostname_locked', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'hostname_locked')
    # ### end Alembic commands ###
