"""add hostname_source to asset

Revision ID: 5dcdaa3ce36e
Revises: aa6ee770020a
Create Date: 2026-07-04 19:20:48.854747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dcdaa3ce36e'
down_revision: Union[str, Sequence[str], None] = 'aa6ee770020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('hostname_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'hostname_source')
    # ### end Alembic commands ###
