"""add network_name to asset interface

Revision ID: aa6ee770020a
Revises: 375c4f8896d8
Create Date: 2026-07-04 18:54:46.617044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa6ee770020a'
down_revision: Union[str, Sequence[str], None] = '375c4f8896d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetinterface', sa.Column('network_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assetinterface', 'network_name')
    # ### end Alembic commands ###
